### ISSUE TITLE
Improved Windows support in XKCP/K12

### ISSUE THREAD

**Issue by gvanas** [oconnor663/kangarootwelve_xkcp.rs#2]
I improved the support of Microsoft Visual Studio in XKCP and K12. For K12 in particular there is now a `generic64noAsm` target that works fine with these tools. 

This new target may therefore advantageously replace the `generic32` target on Windows.

**Comment by oconnor663** [comment]
Thanks for the heads up! Any more changes planned?

**Comment by gvanas** [comment]
No, nothing planned. For me the K12 code is stable. There could always be a bug fix or so, but I am not actively working on it for the moment…

Anyway, thanks already!

**Comment by oconnor663** [comment]
I just released version 0.1.2, including all the latest changes from upstream. There are now `k12sum` binaries available [on the releases page](https://github.com/oconnor663/kangarootwelve_xkcp.rs/releases).

**Comment by gvanas** [comment]
Wow, great, big thanks!
