### ISSUE TITLE
`k12` crate

### ISSUE THREAD

**Issue by tarcieri** [oconnor663/kangarootwelve_xkcp.rs#3]
Hello!

The [RustCrypto Project](https://github.com/rustcrypto/) has recently published an experimental new pure Rust [`k12` crate](https://github.com/RustCrypto/hashes/tree/master/k12).

Performance at this point is ok:

```
test bench1_10    ... bench:           9 ns/iter (+/- 1) = 1111 MB/s
test bench2_100   ... bench:          45 ns/iter (+/- 26) = 2222 MB/s
test bench3_1000  ... bench:         530 ns/iter (+/- 140) = 1886 MB/s
test bench4_10000 ... bench:       5,071 ns/iter (+/- 5,848) = 1971 MB/s
```

The implementation is suboptimal in a few ways, namely it buffers the entire message to be hashed before computing the XOF's internal state. We would definitely love to have some contributors on the crate who would be interested in fixing that (and ideally removing the `alloc` requirement thereby making it `no_std` friendly).

Thought I'd let you know in case this is something you'd be interested in.

**Comment by oconnor663** [comment]
Thanks for the heads up. I don't think I'll have bandwidth for that, but I'd be happy to hop on a call or whatever with anyone who wants to talk about the design. Incidentally, I should admit that I've never actually _implemented_ K12 myself :) I've only wrapped the upstream implementation.

By the way, those benchmark figures are surprising. How is it possible to run the compression function in 9 ns? Am I misinterpreting what an iteration means?

**Comment by tarcieri** [comment]
Thanks for taking a look.

I agree those numbers are surprising: they're closer to what I'd expect for AES-NI than anything written in software (especially unoptimized).

It is an experimental implementation, after all 😉

**Comment by oconnor663** [comment]
Oh it's probably this: https://github.com/RustCrypto/traits/blob/master/digest/src/dev.rs#L228-L230

The benchmarks only call `update`, but because this implementation defers all of its work to finalization, this is basically just benchmarking `extend_from_slice` :)

**Comment by tarcieri** [comment]
Aha, good catch!
